### ISSUE TITLE
能動有利から受動有利に変更

### ISSUE THREAD

**Issue by syadoumi** [t4t5u0/dice-buttle#5]
swなどの達成値の比べあいは基本的に受動有利なので、受動有利に設定されている方が使い勝手が良いと思われる。

**Comment by t4t5u0** [comment]
確率も受動側の出したほうが嬉しい？

**Comment by syadoumi** [comment]
> 確率も受動側の出したほうが嬉しい？
分かりやすくなって嬉しいけど、なくてもいい。
